# Generated by Django 3.2.6 on 2021-08-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_board', '0006_alter_post_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
